package ar.edu.unlu.diezmil.modelo;

public enum Estado {
	CAMBIO_LISTA_JUGADORES, 
	CAMBIO_ESTADO,
	CAMBIO_JUGADOR,
	NUEVA_TIRADA,
	HAY_GANADOR,
	FALTAN_JUGADORES, 
	PERDIO_TURNO, 
	CONTINUA_TURNO
}
